package com.mega.mvc06;

public class Problem06Main {

	public static void main(String[] args) {
		problem06 error= new problem06();
		try {
			error.call();
		} catch (Exception e) {
			System.out.println("호출한 곳에서 알아서 처리함......");
		}
		System.out.println("에러 발생 후 실행 될까요 ?");
		System.out.println("에러 발생 후 실행 될까요 ?");
		System.out.println("에러 발생 후 실행 될까요 ?");
		System.out.println("에러 발생 후 실행 될까요 ?");
		System.out.println("에러 발생 후 실행 될까요 ?");
		System.out.println("에러 발생 후 실행 될까요 ?");
		System.out.println("에러 발생 후 실행 될까요 ?");
	}

}
